"""test table delete

Revision ID: 6dfb809d0fc5
Revises: 871d233db177
Create Date: 2023-04-12 15:44:21.737629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfb809d0fc5'
down_revision = '871d233db177'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
