"""test table update

Revision ID: 871d233db177
Revises: 1ae46a35881f
Create Date: 2023-04-12 15:12:04.171958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871d233db177'
down_revision = '1ae46a35881f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
