"""new data

Revision ID: c650c93b580d
Revises: 0fdb50d1eb8b
Create Date: 2023-04-07 02:00:09.297582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c650c93b580d'
down_revision = '0fdb50d1eb8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
